"""
This type stub file was generated by pyright.
"""

from commands2 import Subsystem
from .controller_constants import Input

class SC_Controller(Subsystem):
    '''
    Controller class that wraps a GenericHID and provides the following features:
    - Implicit conversion from any input type to any other input type (such as using a trigger as a button)
    - Deadband application for axes
    - Edge detection for all input types
    - Error handling that doesn't halt execution or spam warnings during competition
    '''
    ERROR_TIMEOUT: int = ...
    def __init__(self, port: int, axis_limit: float = ..., trigger_limit: float = ..., axis_deadband: float = ...) -> None:
        ...
    
    def periodic(self): # -> None:
        ...
    
    def set_left_rumble(self, rumble: float) -> None:
        '''
        Set the left rumble intensity of the controller.
        '''
        ...
    
    def set_right_rumble(self, rumble: float) -> None:
        '''
        Set the right rumble intensity of the controller.
        '''
        ...
    
    def set_rumble(self, rumble: float) -> None:
        '''
        Set the rumble intensity of the controller.
        '''
        ...
    
    def get_button(self, input: Input, input_states: dict | None = ...) -> bool:
        '''
        Get the value of an input as True/False.
        '''
        ...
    
    def get_button_pressed(self, input: Input) -> bool:
        '''
        Get whether an input was pressed this cycle.
        '''
        ...
    
    def get_button_released(self, input: Input) -> bool:
        '''
        Get whether an input was released this cycle.
        '''
        ...
    
    def get_axis(self, input: Input, input_states: dict | None = ...) -> float:
        '''
        Get the value of an input on a scale of -1.0 to 1.0 (or 0.0 to 1.0 for some inputs).
        '''
        ...
    
    def get_axis_change(self, input: Input) -> float:
        '''
        Get the change in value of an input since last cycle.
        '''
        ...
    
    def get_angle(self, input: Input, input_states: dict | None = ...) -> float:
        '''
        Get the angle of an input in degrees from 0 to 360 or -1 for neutral.
        While this supports any input type, it is primarily intended for use with AXIS_ANGLE and POV_ANGLE types.
        '''
        ...
    
    def get_angle_change(self, input: Input) -> float:
        '''
        Get the change in angle of an input since last cycle.
        '''
        ...
    


