from dataclasses import dataclass
from pathplannerlib.path import PathConstraints
from wpimath.units import degrees as degrees, inches as inches, seconds as seconds

@dataclass(frozen=True)
class PathfindingConfig:
    FINAL_ALIGNMENT_DISTANCE: inches = ...
    PATH_CONSTRAINTS: PathConstraints = ...

@dataclass(frozen=True)
class FinalAlignmentConfig:
    TIMEOUT: seconds = ...
    POSITION_TOLERANCE: inches = ...
    ROTATION_TOLERANCE: degrees = ...
