import commands2
from .config import FinalAlignmentConfig as FinalAlignmentConfig
from pathplannerlib.controller import PathFollowingController as PathFollowingController
from typing import Callable
from wpimath.geometry import Pose2d as Pose2d
from wpimath.kinematics import ChassisSpeeds

class FinalAlignmentCommand(commands2.Command):
    def __init__(self, target_pose: Pose2d, drive_controller: PathFollowingController, pose_supplier: Callable[[], Pose2d], output: Callable[[ChassisSpeeds], None], drivetrain_subsystem: commands2.Subsystem, config: FinalAlignmentConfig | None = None) -> None: ...
    @property
    def config(self) -> FinalAlignmentConfig: ...
    @config.setter
    def config(self, config: FinalAlignmentConfig) -> None: ...
    def initialize(self) -> None: ...
    def execute(self) -> None: ...
    def end(self, interrupted: bool) -> None: ...
    def isFinished(self) -> bool: ...
