import commands2
from ..datatypes.pathing_datatypes import SC_ApriltagTarget as SC_ApriltagTarget
from .config import FinalAlignmentConfig as FinalAlignmentConfig, PathfindingConfig as PathfindingConfig
from .final_alignment_command import FinalAlignmentCommand as FinalAlignmentCommand
from pathplannerlib.controller import PathFollowingController as PathFollowingController
from typing import Callable, Iterable
from wpimath.geometry import Pose2d as Pose2d
from wpimath.kinematics import ChassisSpeeds as ChassisSpeeds
from wpimath.units import inches as inches

class SC_Pathfinding:
    config: PathfindingConfig
    alignment_config: FinalAlignmentConfig
    def __init__(self, drivetrain_subsystem: commands2.Subsystem, pose_supplier: Callable[[], Pose2d], output: Callable[[ChassisSpeeds], None], alignment_controller: PathFollowingController) -> None: ...
    def get_final_alignment_command(self, target: Pose2d) -> commands2.Command: ...
    def get_near_pose_command(self, target: Pose2d, distance: inches) -> commands2.Command: ...
    def get_pathfollow_command(self, start_pose: Pose2d, target: Pose2d, intermediate_points: Iterable[Pose2d] | None = None) -> commands2.Command: ...
    def get_pathfind_command(self, target: Pose2d) -> commands2.Command: ...
    def pathfind_to_pose(self, target_pose: Pose2d, safe_distance: inches = 999, defer: bool = False) -> commands2.Command: ...
    def pathfind_to_target(self, target: SC_ApriltagTarget, defer: bool = False) -> commands2.Command: ...
