"""
This type stub file was generated by pyright.
"""

__all__ = ["SC_LauncherSpeed", "SC_PIDConfig", "SC_SolenoidConfig", "SC_DoubleSolenoidConfig", "SC_AngularFeedForwardConfig", "SC_LinearFeedForwardConfig", "SC_MotorConfig", "SC_SwerveConfig", "SC_SwerveCurrentConfig", "SC_DrivePIDConfig", "SC_SteerPIDConfig", "SC_CameraConfig", "SC_CameraResults", "SC_ApriltagTarget"]
