"""
This type stub file was generated by pyright.
"""

__all__ = ["AngularPositionMotor", "LinearPositionMotor", "PowerMotor", "VelocityMotor", "SC_LauncherSpeed", "SC_PIDConfig", "SC_SolenoidConfig", "SC_DoubleSolenoidConfig", "SC_AngularFeedForwardConfig", "SC_LinearFeedForwardConfig", "SC_MotorConfig", "SC_PositionControl", "SC_TrapezoidConfig"]
