"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from wpimath.units import degrees, inches, seconds
from pathplannerlib.path import PathConstraints

@dataclass(frozen=True)
class PathfindingConfig:
    FINAL_ALIGNMENT_DISTANCE: inches = ...
    PATH_CONSTRAINTS: PathConstraints = ...


@dataclass(frozen=True)
class FinalAlignmentConfig:
    TIMEOUT: seconds = ...
    POSITION_TOLERANCE: inches = ...
    ROTATION_TOLERANCE: degrees = ...


