"""
This type stub file was generated by pyright.
"""

import commands2
from typing import Callable
from wpimath.geometry import Pose2d
from wpimath.kinematics import ChassisSpeeds
from pathplannerlib.controller import PathFollowingController
from .config import FinalAlignmentConfig

class FinalAlignmentCommand(commands2.Command):
    """
    A command that uses the drivetrain to do a precise alignment to a target pose
    Used by SC_Pathfinding to align the robot to the target pose,
        commonly after using pathfinding to roughly reach a pose
    
    Parameters:
        - target_pose (Pose2d): The target pose
        - drive_controller (PathFollowingController): The pathplanner drive controller to use for alignment
        - pose_supplier (Callable[[], Pose2d]): Function to get the robot's current pose
        - output (Callable[[ChassisSpeeds], None]): Function to output chassis speeds to the drivetrain
        - drivetrain_subsystem (Subsystem): The drivetrain subsystem for adding command requirements
    """
    def __init__(self, target_pose: Pose2d, drive_controller: PathFollowingController, pose_supplier: Callable[[], Pose2d], output: Callable[[ChassisSpeeds], None], drivetrain_subsystem: commands2.Subsystem, config: FinalAlignmentConfig | None = ...) -> None:
        ...
    
    @property
    def config(self) -> FinalAlignmentConfig:
        """
        Returns the configuration for the final alignment command

        Returns:
            - FinalAlignmentConfig: The configuration
        """
        ...
    
    @config.setter
    def config(self, config: FinalAlignmentConfig) -> None:
        """
        Sets the configuration for the final alignment command

        Parameters:
            - config (FinalAlignmentConfig): The new configuration
        """
        ...
    
    def initialize(self) -> None:
        ...
    
    def execute(self) -> None:
        ...
    
    def end(self, interrupted: bool) -> None:
        ...
    
    def isFinished(self) -> bool:
        ...
    


