"""
This type stub file was generated by pyright.
"""

import commands2
from typing import Callable, Iterable
from wpimath.geometry import Pose2d
from wpimath.kinematics import ChassisSpeeds
from wpimath.units import inches
from pathplannerlib.controller import PathFollowingController
from ..datatypes.pathing_datatypes import SC_ApriltagTarget

class SC_Pathfinding:
    """
    A library for handling the pathfinding of the robot

    Can do april tag math, and return commands for pathfinding

    Parameters:
        - drivetrain_subsystem (Subsystem): The drivetrain subsystem for adding command requirements
        - pose_supplier (Callable[[], Pose2d]): Function to get the robot's current pose
        - output (Callable[[ChassisSpeeds], None]): Function to output chassis speeds to the drivetrain
        - alignment_controller (PathFollowingController): The controller to use for final alignment
    """
    def __init__(self, drivetrain_subsystem: commands2.Subsystem, pose_supplier: Callable[[], Pose2d], output: Callable[[ChassisSpeeds], None], alignment_controller: PathFollowingController) -> None:
        ...
    
    def get_final_alignment_command(self, target: Pose2d) -> commands2.Command:
        """
        Returns a command to align the robot to a target pose

        Parameters:
            - target (Pose2d): The target pose to align to
            - defer (bool): Whether to defer the command

        Returns:
            - Command: The command to align to the target
        """
        ...
    
    def get_near_pose_command(self, target: Pose2d, distance: inches) -> commands2.Command:
        """
        Returns a command that does nothing and waits until the robot is within a distance, then exits
        Intended to be used in parallel with a pathing command so once the robot is close to its end position, 
            the command group will exit and the final alignment command can take over

        Parameters:
            - target (Pose2d): The target pose to align to
            - distance (inches): The distance to wait before exiting

        Returns:
            - Command: The command to align to the target
        """
        ...
    
    def get_pathfollow_command(self, start_pose: Pose2d, target: Pose2d, intermediate_points: Iterable[Pose2d] | None = ...) -> commands2.Command:
        """
        Returns a command that drives from start pose to target pose, without opstacle avoidance and optionally through intermediate points

        Parameters:
            - start_pose (Pose2d): The starting pose
            - target (Pose2d): The target pose
            - intermediate_points (list[Pose2d] | None): Optional intermediate points to drive through

        Returns:
            - Command: The command to drive through all the points
        """
        ...
    
    def get_pathfind_command(self, target: Pose2d) -> commands2.Command:
        """
        Returns a command that drives to target pose, avoiding obstacles.  
        This command is NOT safe for use in autonomous, use pathfind_to_pose instead

        Parameters:
            - target (Pose2d): The target pose

        Returns:
            - Command: The command to drive to the target
        """
        ...
    
    def pathfind_to_pose(self, target_pose: Pose2d, safe_distance: inches = ..., defer: bool = ...) -> commands2.Command:
        """
        Returns a command that creates a path to drive to the given target pose.
        This command is safe for use in autonomous

        Parameters:
            - target_pose (Pose2d): The target pose to drive to
            - defer (bool): Whether to defer the command

        Returns:
            - Command: The command to drive to the target pose
        """
        ...
    
    def pathfind_to_target(self, target: SC_ApriltagTarget, defer: bool = ...) -> commands2.Command:
        """
        Returns a command that creates a path to drive to the nearest point on the given target.  
        This command is safe for use in autonomous

        Parameters:
            - target (SC_ApriltagTarget): The april tag target to drive to
            - start_pose (Pose2d | None): The starting pose. If None, will use the robot's current pose.

        Returns:
            - Command: The command to drive to the nearest point on the target
        """
        ...
    


