"""
This type stub file was generated by pyright.
"""

from typing import Iterable
from wpimath.geometry import Pose2d
from robotpy_apriltag import AprilTagField
from photonlibpy.photonPoseEstimator import PoseStrategy
from ..datatypes.pathing_datatypes import SC_CameraConfig, SC_CameraResults

class SC_Vision:
    """
    A class for handling vision processing

    Will return the estimated pose of the robot, based on the given camera configs

    Parameters:
        - camera_configs (list[SC_CameraConfig]): A list of camera configs
        - april_tag_layout (AprilTagFieldLayout): The april tag field layout
        - pose_strategy (PoseStrategy): The pose strategy
        - single_tag_st_devs (tuple[float, float, float]): The standard deviations for single tag detection
        - multi_tag_st_devs (tuple[float, float, float]): The standard deviations for multi tag detection
    """
    def __init__(self, camera_configs: Iterable[SC_CameraConfig], april_tag_field: AprilTagField, pose_strategy: PoseStrategy, single_tag_st_devs: tuple[float, float, float], multi_tag_st_devs: tuple[float, float, float]) -> None:
        ...
    
    def get_camera_results(self, current_pose: Pose2d) -> list[SC_CameraResults]:
        """
        Returns the camera results, including the estimated pose, timestamp, and standard deviation

        Parameters:
            - current_pose (Pose2d): The current pose of the robot

        Returns:
            - list[SC_CameraResults]: A list of camera results
        """
        ...
    


