from ..datatypes.motion_datatypes import SC_AngularFeedForwardConfig as SC_AngularFeedForwardConfig, SC_LinearFeedForwardConfig as SC_LinearFeedForwardConfig, SC_MotorConfig as SC_MotorConfig, SC_PIDConfig as SC_PIDConfig, SC_TrapezoidConfig as SC_TrapezoidConfig
from .power_motor import PowerMotor as PowerMotor
from enum import Enum
from phoenix6.hardware import CANcoder as CANcoder
from typing import override
from wpimath.units import degrees as degrees, degrees_per_second as degrees_per_second

class State(Enum):
    POWER = 0
    POSITION = 1

class AngularPositionMotor(PowerMotor):
    STALL_LIMIT: float
    STALL_THRESHOLD: float
    def __init__(self, motor_config: SC_MotorConfig, pid_config: SC_PIDConfig, feed_forward_config: SC_AngularFeedForwardConfig | SC_LinearFeedForwardConfig, trapezoid_config: SC_TrapezoidConfig, angle_tolerance: degrees, gear_ratio: float = 1.0, external_encoder: CANcoder | None = None) -> None: ...
    @override
    def periodic(self) -> None: ...
    def at_target_position(self) -> bool: ...
    def get_position(self) -> degrees: ...
    def get_velocity(self) -> degrees_per_second: ...
    def set_power(self, power: float) -> None: ...
    def set_target_position(self, position: degrees) -> None: ...
    @override
    def print_diagnostics(self) -> None: ...
