from ..datatypes import SC_MotorConfig as SC_MotorConfig
from commands2 import Subsystem

class PowerMotor(Subsystem):
    STALL_LIMIT: float
    STALL_THRESHOLD: float
    def __init__(self, motor_config: SC_MotorConfig) -> None: ...
    @property
    def device_id(self) -> int: ...
    def periodic(self) -> None: ...
    def set_power(self, power: float) -> None: ...
    def set_brake_mode(self) -> None: ...
    def set_coast_mode(self) -> None: ...
    def get_stall_percentage(self) -> float: ...
    def follow(self, motor: PowerMotor) -> None: ...
    def get_stalled(self) -> bool: ...
    def print_diagnostics(self) -> None: ...
