from ..datatypes import SC_LauncherSpeed as SC_LauncherSpeed, SC_LinearFeedForwardConfig as SC_LinearFeedForwardConfig, SC_MotorConfig as SC_MotorConfig, SC_PIDConfig as SC_PIDConfig
from .power_motor import PowerMotor as PowerMotor
from typing import override

class VelocityMotor(PowerMotor):
    STALL_LIMIT: float
    STALL_THRESHOLD: float
    def __init__(self, motor_config: SC_MotorConfig, pid_config: SC_PIDConfig, feed_forward_config: SC_LinearFeedForwardConfig, gear_ratio: float, tolerance: float) -> None: ...
    @override
    def periodic(self) -> None: ...
    def set_speed(self, speed: SC_LauncherSpeed) -> None: ...
    def at_target_speed(self) -> bool: ...
    @override
    def set_power(self, power: float) -> None: ...
    @override
    def print_diagnostics(self) -> None: ...
