"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import override
from wpimath.units import degrees, degrees_per_second
from phoenix6.hardware import CANcoder
from .power_motor import PowerMotor
from ..datatypes.motion_datatypes import SC_AngularFeedForwardConfig, SC_LinearFeedForwardConfig, SC_MotorConfig, SC_PIDConfig, SC_TrapezoidConfig

class State(Enum):
    POWER = ...
    POSITION = ...


class AngularPositionMotor(PowerMotor):
    '''
    Defines a base motor class for angular position control

    Parameters:
        motor_config: SC_MotorConfig
        current_config: SC_CurrentConfig
        pid_config: SC_PIDConfig
        feed_forward_config: SC_AngularFeedForwardConfig
        trapezoid_config: SC_TemplateMotorTrapezoidConfig
        angle_tolerance: degrees
        gear_ratio: float = 1.0
        external_encoder: CANcoder | None = None
    '''
    STALL_LIMIT: float = ...
    STALL_THRESHOLD: float = ...
    def __init__(self, motor_config: SC_MotorConfig, pid_config: SC_PIDConfig, feed_forward_config: SC_AngularFeedForwardConfig | SC_LinearFeedForwardConfig, trapezoid_config: SC_TrapezoidConfig, angle_tolerance: degrees, gear_ratio: float = ..., external_encoder: CANcoder | None = ...) -> None:
        ...
    
    @override
    def periodic(self) -> None:
        '''
        Handles controlling the motors in position mode and printing diagnostics
        '''
        ...
    
    def at_target_position(self) -> bool:
        '''
        Returns whether the motor is at the target angle or not

        Returns:
            - bool: True if the motor is at the target angle, False otherwise
        '''
        ...
    
    def get_position(self) -> degrees:
        '''
        Returns the current angle of the motor

        Returns:
            - degrees: The current angle of the motor
        '''
        ...
    
    def get_velocity(self) -> degrees_per_second:
        '''
        Returns the current velocity of the motor

        Returns:
            - degrees_per_second: The current velocity of the motor
        '''
        ...
    
    def set_power(self, power: float) -> None:
        '''
        Sets the power of the motor

        Parameters:
            - power (float): The power to set the motor to
        '''
        ...
    
    def set_target_position(self, position: degrees) -> None:
        '''
        Sets the target angle of the motor

        Parameters:
            - angle (degrees): The angle to set the motor to
        '''
        ...
    
    @override
    def print_diagnostics(self) -> None:
        '''
        Prints diagnostic information to Smart Dashboard
        '''
        ...
    


