"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import final, override
from wpimath.units import inches
from phoenix6.hardware import CANcoder
from .angular_pos_motor import AngularPositionMotor
from ..datatypes.motion_datatypes import SC_LinearFeedForwardConfig, SC_MotorConfig, SC_PIDConfig, SC_TrapezoidConfig

inches_per_second = float
class State(Enum):
    POWER = ...
    POSITION = ...


@final
class LinearPositionMotor(AngularPositionMotor):
    '''
    Defines a base motor class for angular position control

    Parameters:
        motor_config: SC_MotorConfig
        current_config: SC_TemplateMotorCurrentConfig
        pid_config: SC_PIDConfig
        feed_forward_config: SC_LinearFeedForwardConfig
        trapezoid_config: SC_TemplateMotorTrapezoidConfig
        position_tolerance: feet
        gear_ratio: float = 1.0
        external_encoder: CANcoder | None = None
    '''
    STALL_LIMIT: float = ...
    STALL_THRESHOLD: float = ...
    def __init__(self, motor_config: SC_MotorConfig, pid_config: SC_PIDConfig, feed_forward_config: SC_LinearFeedForwardConfig, trapezoid_config: SC_TrapezoidConfig, position_tolerance: inches, pulley_radius: inches, gear_ratio: float = ..., external_encoder: CANcoder | None = ...) -> None:
        ...
    
    def at_target_position(self) -> bool:
        '''
        Returns whether the motor is at the target position or not

        Returns:
            - bool: True if the motor is at the target position, False otherwise
        '''
        ...
    
    def get_position(self) -> inches:
        '''
        Returns the current position of the motor

        Returns:
            - feet: The current angle of the motor
        '''
        ...
    
    @override
    def get_velocity(self) -> inches_per_second:
        '''
        Returns the current velocity of the motor

        Returns:    
            - feet_per_second: The current velocity of the motor
        '''
        ...
    
    @override
    def set_target_position(self, position: inches) -> None:
        '''
        Sets the target position of the motor

        Parameters:
            - position (feet): The angle to set the motor to
        '''
        ...
    
    @override
    def print_diagnostics(self) -> None:
        '''
        Prints diagnostic information to Smart Dashboard
        '''
        ...
    


