"""
This type stub file was generated by pyright.
"""

from commands2 import Subsystem
from ..datatypes import SC_MotorConfig

class PowerMotor(Subsystem):
    '''
    Creates a motor template class that can be used to create a 
        base motor that simply powers forwards or backwards at a given power

    Parameters:
        - motor_config (SC_MotorConfig): The configuration for the motor
        - current_config (SC_TemplateMotorCurrentConfig): Current limit settings for the motor
    '''
    STALL_LIMIT: float = ...
    STALL_THRESHOLD: float = ...
    def __init__(self, motor_config: SC_MotorConfig) -> None:
        ...
    
    @property
    def device_id(self) -> int:
        ...
    
    def periodic(self) -> None:
        '''
        Handles printing diagnostic information to Smart Dashboard
        '''
        ...
    
    def set_power(self, power: float) -> None:
        '''
        Sets the power of the motor

        Parameters:
            - power (float): The power to set the motor to
        '''
        ...
    
    def set_brake_mode(self) -> None:
        '''
        Sets the motor to brake mode
        '''
        ...
    
    def set_coast_mode(self) -> None:
        '''
        Sets the motor to coast mode
        '''
        ...
    
    def get_stall_percentage(self) -> float:
        '''
        Returns the percentage of stall current being drawn by the motor

        Returns:
            - float: The percentage of stall current being drawn by the motor
        '''
        ...
    
    def follow(self, motor: PowerMotor) -> None:
        ...
    
    def get_stalled(self) -> bool:
        '''
        Returns whether the motor is stalled or not

        Returns:
            - bool: True if the motor is stalled, False otherwise
        '''
        ...
    
    def print_diagnostics(self) -> None:
        '''
        Prints diagnostic information to Smart Dashboard
        '''
        ...
    


