"""
This type stub file was generated by pyright.
"""

from typing import override
from ..datatypes import SC_LauncherSpeed, SC_LinearFeedForwardConfig, SC_MotorConfig, SC_PIDConfig
from .power_motor import PowerMotor

class VelocityMotor(PowerMotor):
    '''
    Creates a motor template class that represents a motor that can be set to a target speed

    Parameters:
        - motor_config (SC_MotorConfig): The configuration for the motor
        - current_config (SC_TemplateMotorCurrentConfig): Current limit settings for the motor
        - pid_config (SC_PIDConfig): The configuration for the PID controller
        - gear_ratio (float): The gear ratio of the motor
        - tolerance (float): The tolerance for the target speed to consider it reached
    '''
    STALL_LIMIT: float = ...
    STALL_THRESHOLD: float = ...
    def __init__(self, motor_config: SC_MotorConfig, pid_config: SC_PIDConfig, feed_forward_config: SC_LinearFeedForwardConfig, gear_ratio: float, tolerance: float) -> None:
        ...
    
    @override
    def periodic(self) -> None:
        '''
        Handles Smart Dashboard diagnostic information and actually controlling the motors
        '''
        ...
    
    def set_speed(self, speed: SC_LauncherSpeed) -> None:
        '''
        Sets the target speed for the motor

        Parameters:
            - speed (SC_TemplateMotorVelocityControl): The speed and power to set the motor to
        '''
        ...
    
    def at_target_speed(self) -> bool:
        '''
        Checks if the motor is at the target speed

        Returns:
            - bool: True if the motor is at the target speed, False otherwise
        '''
        ...
    
    @override
    def set_power(self, power: float) -> None:
        '''
        Sets the power of the motor for testing purposes

        Parameters:
            - power (float): The power to set the motor to
        '''
        ...
    
    @override
    def print_diagnostics(self) -> None:
        '''
        Prints diagnostic information to Smart Dashboard
        '''
        ...
    


