"""
This type stub file was generated by pyright.
"""

from wpilib import Color
from wpimath.units import meters_per_second
from typing import Iterable
from enum import Enum

class PatternState(Enum):
    fill = ...
    empty = ...


class ColorStack:
    def __init__(self, colors: Iterable[Color], bar_size: int, velocity: meters_per_second, fill_size: int, empty_size: int, gamma: float) -> None:
        ...
    
    def reset(self): # -> None:
        ...
    


