"""
This type stub file was generated by pyright.
"""

from wpilib import Color
from wpimath.units import meters, meters_per_second
from typing import Iterable

class ColorWave:
    def __init__(self, colors: Iterable[Color], led_spacing: meters, wavelength: meters, gamma: float, velocity: meters_per_second, bar_size: int) -> None:
        ...
    


