"""
This type stub file was generated by pyright.
"""

from wpilib import Color
from wpimath.units import meters, meters_per_second, meters_per_second_squared
from typing import Iterable
from enum import Enum

class PatternState(Enum):
    fill = ...
    empty = ...


class FallingSand:
    def __init__(self, colors: Iterable[Color], bar_size: int, led_spacing: meters, intake_velocity: meters_per_second, exit_acceleration: meters_per_second_squared, fill_size: int, gamma: float) -> None:
        ...
    
    def reset(self): # -> None:
        ...
    


