"""
This type stub file was generated by pyright.
"""

class Fire:
    def __init__(self, height, sparks, delay, n_leds) -> None:
        """
        :param height: The height of the fire. Smaller values = taller flames.
        :param sparks: Number of sparks to ignite. Higher = more frequent sparks.
        :param delay: Delay between sparks. Smaller = shorter delays.
        :param n_leds: Number of LEDs.
        """
        ...
    
    def apply_to(self, data): # -> None:
        ...
    
    def reset(self): # -> None:
        ...
    


