from robotpy_apriltag import AprilTagFieldLayout as AprilTagFieldLayout
from typing import Iterable
from wpimath.geometry import Pose2d, Pose3d as Pose3d

def get_april_tag_poses(april_tag_ids: Iterable[int], layout: AprilTagFieldLayout) -> list[Pose2d]: ...
def apply_offset_to_pose(pose: Pose2d, offset: Pose2d) -> Pose2d: ...
def apply_offsets_to_poses(poses: Iterable[Pose2d], offsets: Iterable[Pose2d]) -> list[Pose2d]: ...
def get_nearest_pose(current_position: Pose2d, poses: Iterable[Pose2d]) -> Pose2d: ...
