from .controller_constants import Input as Input
from commands2 import Subsystem

class SC_Controller(Subsystem):
    ERROR_TIMEOUT: int
    def __init__(self, port: int, axis_limit: float = 0.5, trigger_limit: float = 0.5, axis_deadband: float = 0.02) -> None: ...
    def periodic(self) -> None: ...
    def set_left_rumble(self, rumble: float) -> None: ...
    def set_right_rumble(self, rumble: float) -> None: ...
    def set_rumble(self, rumble: float) -> None: ...
    def get_button(self, input: Input, input_states: dict | None = None) -> bool: ...
    def get_button_pressed(self, input: Input) -> bool: ...
    def get_button_released(self, input: Input) -> bool: ...
    def get_axis(self, input: Input, input_states: dict | None = None) -> float: ...
    def get_axis_change(self, input: Input) -> float: ...
    def get_angle(self, input: Input, input_states: dict | None = None) -> float: ...
    def get_angle_change(self, input: Input) -> float: ...
