"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Iterable
from wpimath.units import inches, seconds
from wpilib import DriverStation
from wpimath.geometry import Pose2d, Transform3d
from robotpy_apriltag import AprilTagField
from ..pose_manipulation.pose_manipulation import *

@dataclass(frozen=True)
class SC_CameraConfig:
    name: str
    position: Transform3d
    enabled: bool = ...


@dataclass(frozen=True)
class SC_CameraResults:
    vision_measurement: Pose2d
    timestamp: seconds
    standard_deviation: tuple[float, float, float]
    ...


class SC_ApriltagTarget:
    def __init__(self, apriltag_ids: Iterable[int], offsets: Iterable[Pose2d], safe_distance: inches, field: AprilTagField, red_apriltag_ids: Iterable | None = ...) -> None:
        """
        A class for holding all information needed to pathfind to a field element

        Target poses are calculated by applying offsets to april tag poses

        Positive X is in front of the april tag, positive Y is to the right of the april tag (when facing the tag), and

        0 degrees rotation is facing away from the april tag, positive rotation is counter-clockwise

        Parameters:
            - apriltag_ids (Iterable[int]): April tag ids that can be used by both alliances
            - offsets (Iterable[Pose2d]): The offsets to apply to the april tag poses
            - safe_distance (inches): The safe distance to maintain from the target
            - field (AprilTagField): The field layout to use
            - red_apriltag_ids (Iterable[int] | None): If provided, these april tag ids will be used for the red alliance and the apriltag_ids will be used for the blue alliance
        """
        ...
    
    @property
    def targets(self) -> list[Pose2d]:
        """
        Returns the target poses for the current alliance
        Returns:
            - list[Pose2d]: The target poses for the current alliance
        """
        ...
    
    @property
    def safe_distance(self) -> inches:
        """
        Returns the safe distance to maintain from the target

        Returns:
            - inches: The safe distance
        """
        ...
    
    def get_targets_for_alliance(self, alliance: DriverStation.Alliance) -> list[Pose2d]:
        """
        Returns the target poses for the specified alliance

        Parameters:
            - alliance (DriverStation.Alliance | None): The alliance to use. If None, will use the current alliance. If there's no current alliance, will default to blue

        Returns:
            - list[Pose2d]: The target poses for the specified alliance
        """
        ...
    
    def get_nearest(self, current_position: Pose2d) -> Pose2d:
        """
        Returns the nearest target pose to the robot's current position

        Parameters:
            - current_position (Pose2d): The robot's current position

        Returns:
            - Pose2d: The nearest target pose
        """
        ...
    


